// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK6IB92febYbo8NzZQLOA_4vO2Ro0hr30',
    appId: '1:1032411645202:web:ea0bf4b0048e8700b51fcb',
    messagingSenderId: '1032411645202',
    projectId: 'no-starve-project',
    authDomain: 'no-starve-project.firebaseapp.com',
    storageBucket: 'no-starve-project.appspot.com',
    measurementId: 'G-KDW9D4QG00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPz9yTL9NfAgedRWAVb9QnOQKRbH3eGm4',
    appId: '1:1032411645202:android:58504ae1855d48e4b51fcb',
    messagingSenderId: '1032411645202',
    projectId: 'no-starve-project',
    storageBucket: 'no-starve-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg1PregD_ufG4BoDHk6bQcv6oZMKIirrA',
    appId: '1:1032411645202:ios:d57406c0ea67eaf2b51fcb',
    messagingSenderId: '1032411645202',
    projectId: 'no-starve-project',
    storageBucket: 'no-starve-project.appspot.com',
    iosClientId: '1032411645202-cpn1uoqvtt3gpiu0e68gmngjf40chv3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.noStarve',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg1PregD_ufG4BoDHk6bQcv6oZMKIirrA',
    appId: '1:1032411645202:ios:541d423e464e2551b51fcb',
    messagingSenderId: '1032411645202',
    projectId: 'no-starve-project',
    storageBucket: 'no-starve-project.appspot.com',
    iosClientId: '1032411645202-8daugr6lr37bsnqc3ldfguugn20ugpu2.apps.googleusercontent.com',
    iosBundleId: 'com.example.noStarve.RunnerTests',
  );
}
